// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $feedback from "./routes/feedback.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $settings from "./routes/settings.tsx";
import * as $Dashboard from "./islands/Dashboard.tsx";
import * as $FeebackForm from "./islands/FeebackForm.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $InstantUserRatings from "./islands/InstantUserRatings.tsx";
import * as $LoginModal from "./islands/LoginModal.tsx";
import * as $SendEmail from "./islands/SendEmail.tsx";
import * as $SettingsPage from "./islands/SettingsPage.tsx";
import * as $StatCard from "./islands/StatCard.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/feedback.tsx": $feedback,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/settings.tsx": $settings,
  },
  islands: {
    "./islands/Dashboard.tsx": $Dashboard,
    "./islands/FeebackForm.tsx": $FeebackForm,
    "./islands/Header.tsx": $Header,
    "./islands/InstantUserRatings.tsx": $InstantUserRatings,
    "./islands/LoginModal.tsx": $LoginModal,
    "./islands/SendEmail.tsx": $SendEmail,
    "./islands/SettingsPage.tsx": $SettingsPage,
    "./islands/StatCard.tsx": $StatCard,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
